export enum ONBOARDING_STACK {
  SPLASH = 'SPLASH',
  ONBOARDING_STEPS = 'ONBOARDING_STEPS',
  ONBOARDING_LANGUAGE = 'ONBOARDING_LANGUAGE',
}

export enum ROOT_STACK {
  AUTH = 'AUTH',
  HOME = 'HOME',
  ONBOARDING = 'ONBOARDING',
}

export const ROUTES = {
  ONBARDING: ONBOARDING_STACK,
  ROOT: ROOT_STACK,
};
