export enum ONBOARDING_STACK {
  SPLASH = 'SPLASH',
  ONBOARDING_STEPS = 'ONBOARDING_STEPS',
  ONBOARDING_LANGUAGE = 'ONBOARDING_LANGUAGE',
}

export enum ROOT_STACK {
  AUTH = 'AUTH',
  HOME = 'HOME',
  ONBOARDING = 'ONBOARDING',
}

export enum BOTTOM_BAR_STACK {
  HOME = 'APP/HOME',
  STATISTICS = 'APP/STATISTICS',
  WALLET = 'APP/WALLET',
  PROFILE = 'APP/PROFILE',
}

export const ROUTES = {
  ONBARDING: ONBOARDING_STACK,
  ROOT: ROOT_STACK,
  BOTTOM_BAR: BOTTOM_BAR_STACK,
};
