export enum ONBOARDING_STACK {
  SPLASH = 'SPLASH',
  ONBOARDING_LANGUAGE = 'ONBOARDING_LANGUAGE',
  LOTTIE = 'LOTTIE',
  INTERESTS = 'INTERESTS',
}

export enum ROOT_STACK {
  AUTH = 'AUTH',
  HOME = 'HOME',
  ONBOARDING = 'ONBOARDING',
}

export enum BOTTOM_BAR_STACK {
  HOME = 'HOME/HOME',
  STATISTICS = 'HOME/STATISTICS',
  WALLET = 'HOME/WALLET',
  PROFILE = 'HOME/PROFILE',
  EXPLORE = 'HOME/EXPLORE',
}

export enum HOME_STACK {
  ANSWER = 'HOME/ANSWER',
  CREATE_QUESTION = 'HOME/CREATE_QUESTION',
  TOPICS = 'HOME/CREATE_QUESTION/TOPICS',
  CREATE_TOPIC = 'HOME/CREATE_QUESTION/TOPICS/CREATE_TOPIC',
  EDIT_ACCOUNT = 'HOME/PROFILE/EDIT_ACCOUNT',
  SETTINGS = 'HOME/PROFILE/SETTINGS',
  MY_POSTS = 'HOME/PROFILE/MY_POSTS',
  LANGUAGE = 'HOME/PROFILE/LANGUAGE',
  MY_FOLLOWERS = 'HOME/PROFILE/MY_FOLLOWERS',
  TOPICS_FOLLOWED_BY_ME = 'HOME/PROFILE/TOPICS_FOLLOWED_BY_ME',
  PREVIEW_TOPIC = 'HOME/PREVIEW_TOPIC',
  PREVIEW_USER = 'HOME/PREVIEW_USER',
  PREVIEW_USER_POSTS = 'HOME/PREVIEW_USER/PREVIEW_USER_POSTS',
}

export enum REGISTER_STACK {
  LOG_IN = 'LOG_IN',
  CONFIRM = 'CONFIRM',
  SET_UP = 'SET_UP',
}
