export enum ONBOARDING_STACK {
  SPLASH = 'SPLASH',
  ONBOARDING_LANGUAGE = 'ONBOARDING_LANGUAGE',
  LOTTIE = 'LOTTIE',
  INTERESTS = 'INTERESTS',
}

export enum ROOT_STACK {
  AUTH = 'AUTH',
  HOME = 'HOME',
  ONBOARDING = 'ONBOARDING',
}

export enum BOTTOM_BAR_STACK {
  HOME = 'HOME/HOME',
  STATISTICS = 'HOME/STATISTICS',
  WALLET = 'HOME/WALLET',
  PROFILE = 'HOME/PROFILE',
}

export enum HOME_STACK {
  ANSWER = 'HOME/ANSWER',
  CREATE_QUESTION = 'HOME/CREATE_QUESTION',
  TOPICS = 'HOME/CREATE_QUESTION/TOPICS',
  CREATE_TOPIC = 'HOME/CREATE_QUESTION/TOPICS/CREATE_TOPIC',
  PROFILE_SETTINGS = 'HOME/PROFILE/PROFILE_SETTINGS',
}

export enum REGISTER_STACK {
  LOG_IN = 'LOG_IN',
  CONFIRM = 'CONFIRM',
  SET_UP = 'SET_UP',
}
