export enum ONBOARDING_STACK {
  SPLASH = 'SPLASH',
  ONBOARDING_LANGUAGE = 'ONBOARDING_LANGUAGE',
}

export enum ROOT_STACK {
  AUTH = 'AUTH',
  HOME = 'HOME',
  ONBOARDING = 'ONBOARDING',
}

export enum BOTTOM_BAR_STACK {
  HOME = 'HOME/HOME',
  STATISTICS = 'HOME/STATISTICS',
  WALLET = 'HOME/WALLET',
  PROFILE = 'HOME/PROFILE',
}

export enum REGISTER_STACK {
  LOG_IN = 'LOG_IN',
  CONFIRM = 'CONFIRM',
  SET_UP = 'SET_UP',
}
